#!/bin/sh
#SBATCH --job-name=prime
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks-per-core=1
#SBATCH --partition=lirmm1
#SBATCH --time=00:10:00

echo « Running on: $SLURM_NODELIST »
mpirun ./prime >> result
