#!/bin/bash
#SBATCH --job-name=prime
#SBATCH -N 1 
#SBATCH -n 3
#SBATCH --partition=lirmm1
#SBATCH --time=00:10:00
#SBATCH -o "result"

echo ? Running on: $SLURM_NODELIST
srun ./Prime/prime -p 1 2000000
srun ./Prime/prime -p 1 2000000
srun ./Prime/prime -p 1 2000000
