#!/bin/bash
#SBATCH --job-name=parallel 
#SBATCH --ntasks=3
#SBATCH --partition=lirmm1
#SBATCH --time=00:10:00
#SBATCH -o parallel_%j.out   # File to which STDOUT will be written, including job ID
#SBATCH -e parallel_%j.err   # File to which STDERR will be written, including job ID

EXEC=./Prime/prime
ARG1="-s 1 20001"
ARG2="-s 1 20002"
ARG3="-s 1 20003"

#if [[ $ARGC -lt 2 ]]; then
#	echo "Usage : $0 [EXECUTABLE] [DONNEES] [OPTIONS]"
#	exit 1
#fi

echo "Running on: $SLURM_NODELIST"

srun -n 1 --exclusive $EXEC $ARG1 &
srun -n 1 --exclusive $EXEC $ARG2 &
srun -n 1 --exclusive $EXEC $ARG3 &

wait

echo "All jobs done !"
