#!/bin/bash
#SBATCH --job-name=parallel
#SBATCH --ntasks=3
#SBATCH --partition=lirmm1
#SBATCH --time=00:10:00
#SBATCH -o parallel.out   # File to which STDOUT will be written, including job ID

if [[ $# < 2 ]]; then
	echo "Usage : $0 [EXECUTABLE] [DONNEES]"
	exit
fi

echo "Running on: $SLURM_NODELIST"

STARTTIME=$(date +'%s')

for arg do
	if [[ "$arg" > "1" && "$arg" != "$1" ]]; then
		srun -n 1 --exclusive $1 $arg &
	fi
done

wait

ENDTIME=$(date +'%s')

echo "Executé en $(($ENDTIME - $STARTTIME)) secs"

echo "All jobs done !"
