#!/bin/bash
#SBATCH --job-name=PARALLEL 
#SBATCH --ntasks=3
#SBATCH --partition=lirmm1
#SBATCH --time=00:10:00
#SBATCH -o PARALLEL.out

ARGC=$#
COUNT=0
EXEC=./Prime/prime
ARGS="-s 1 20000"

#if [[ $ARGC -lt 2 ]]; then
#	echo "Usage : $0 [EXECUTABLE] [DONNEES] [OPTIONS]"
#	exit 1
#fi

echo "Running on: $SLURM_NODELIST"

$EXEC $ARGS
#srun -n 1 --exclusive $EXEC 

echo "All jobs done !"
